// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA384nWYoIhQkZpVCE0zx2jii5Vcu101nk',
    appId: '1:889727817900:web:e938df3e5b99b1e5a12709',
    messagingSenderId: '889727817900',
    projectId: 'authtrash',
    authDomain: 'authtrash.firebaseapp.com',
    storageBucket: 'authtrash.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzsLHkEBLyV5EIh7A7IDk_FsHgbCw_wDE',
    appId: '1:889727817900:android:9b5b2e4ff02deaf1a12709',
    messagingSenderId: '889727817900',
    projectId: 'authtrash',
    storageBucket: 'authtrash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbBFP4SBwOJD3PG8KspcKNeqsjWI3YINE',
    appId: '1:889727817900:ios:a05184c6b8b7af15a12709',
    messagingSenderId: '889727817900',
    projectId: 'authtrash',
    storageBucket: 'authtrash.appspot.com',
    iosBundleId: 'com.example.newTrashtrackr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbBFP4SBwOJD3PG8KspcKNeqsjWI3YINE',
    appId: '1:889727817900:ios:a05184c6b8b7af15a12709',
    messagingSenderId: '889727817900',
    projectId: 'authtrash',
    storageBucket: 'authtrash.appspot.com',
    iosBundleId: 'com.example.newTrashtrackr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA384nWYoIhQkZpVCE0zx2jii5Vcu101nk',
    appId: '1:889727817900:web:15a7e1bbf6e41e5da12709',
    messagingSenderId: '889727817900',
    projectId: 'authtrash',
    authDomain: 'authtrash.firebaseapp.com',
    storageBucket: 'authtrash.appspot.com',
  );
}
